services:
  redis:
    image: "redis:6.2.5-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  redisinsight:
    image: "redislabs/redisinsight:1.10.1"
    ports:
      - "8001:8001"
    volumes:
      - "redisinsightdata:/db"
    links:
      - "redis"
volumes:
  redisdata: {}
  redisinsightdata: {}
