apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: redis-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-pv-claim
  labels:
    app: redis-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-db
spec:
  selector:
    matchLabels:
      pod: redis-pod
  template:
    metadata:
      labels:
        app: redis-db
        pod: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:6.2.5-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-vol
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight-deployment
  labels:
    app: redis-db
spec:
  selector:
    matchLabels:
      pod: redis-insight-pod
  template:
    metadata:
      labels:
        app: redis-db
        pod: redis-insight-pod
    spec:
      containers:
        - name: redis-insight
          image: redislabs/redisinsight:1.10.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: /db
              name: redis-vol
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-insight-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-db
spec:
  ports:
    - port: 6379
  selector:
    pod: redis-pod
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  labels:
    app: redis-db
spec:
  type: NodePort
  ports:
    - port: 8001
  selector:
    pod: redis-insight-pod