apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
      app: pgsql
spec:
  selector:
    pod: postgres-pod
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
      app: pgsql
spec:
  type: NodePort
  selector:
    pod: pgadmin-pod
  ports:
    - port: 80    