apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: postgres-pod
  template:
    metadata:
      labels:
        app: pgsql
        pod: postgres-pod
    spec:
      containers:
        - name: postgres
          image: postgres:13.3-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              subPath: data
              name: pgsql
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: pgsql
          persistentVolumeClaim:
            claimName: pgsql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pgadmin-pod
  template:
    metadata:
      labels:
        app: pgsql
        pod: pgadmin-pod
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:5.6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib
              subPath: pgadmin
              name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: dbuser@pgadmin.local
            - name: PGADMIN_DEFAULT_PASSWORD
              value: dbpass
      volumes:
        - name: pgadmin
          persistentVolumeClaim:
            claimName: pgadmin-pv-claim
