apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: content-search-app
spec:
  ports:
    - port: 27017
  selector:
    pod: mongo-pod
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: content-search-app
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    pod: mongo-express-pod
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: content-search-app
spec:
  ports:
    - port: 6379
  selector:
    pod: redis-pod
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  labels:
    app: content-search-app
spec:
  type: NodePort
  ports:
    - port: 8001
  selector:
    pod: redis-insight-pod
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: content-search-app
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    pod: web-pod