apiVersion: v1
kind: Service
metadata:
  name: node-app1-http
  labels:
    app: node-app1
spec:
  ports:
    - port: 80
  selector:
    pod: node-app1-pod
---
apiVersion: v1
kind: Service
metadata:
  name: node-app2-http
  labels:
    app: node-app2
spec:
  ports:
    - port: 80
  selector:
    pod: node-app2-pod
---
apiVersion: v1
kind: Service
metadata:
  name: node-app3-http
  labels:
    app: node-app3
spec:
  ports:
    - port: 80
  selector:
    pod: node-app3-pod   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app-ingress
  annotations:
    kubernetes.io/ingress.class: public
  labels:
    app: node-app
spec:
  rules:
  - host: t4dprep0.databots.cloud
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: node-app1-http
            port:
              number: 80
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: node-app2-http
            port:
              number: 80
      - path: /app3
        pathType: Prefix
        backend:
          service:
            name: node-app3-http
            port:
              number: 80